x-common-service: &common-service
  restart: always

x-java-build: &java-build
  dockerfile: Dockerfile
  args:
    - GITHUB_ACTOR=${GITHUB_ACTOR}
  secrets:
    - GITHUB_TOKEN

x-java-service: &java-service
  <<: *common-service
  environment:
    SERVER_PORT: 8080
  expose:
    - "8080"

x-postgres-dep: &postgres-dep
  postgres:
    condition: service_healthy

x-mongo-dep: &mongo-dep
  mongo:
    condition: service_started

services:
  postgres:
    image: postgres:13.1-alpine
    container_name: studydocs_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: studydocs_media_db
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d studydocs_media_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:7
    container_name: studydocs_mongo
    <<: *common-service
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: studydocs_user_db
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: studydocs_redis
    <<: *common-service
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway:
    image: studydocs-gateway:latest
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: studydocs_gateway
    <<: *common-service
    ports:
      - "8080:8080"
    env_file:
      - ./gateway/.env
    depends_on:
      - redis
      - user-service
      - media-service

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    container_name: studydocs_keycloak
    <<: *common-service
    ports:
      - "8180:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - ./user/keycloak/studydoc-realm-export.json:/opt/keycloak/data/import/studydoc-realm-export.json
    command: start-dev --import-realm

  user-service:
    <<: *java-service
    image: studydocs-user-service:latest
    container_name: studydocs_user_service
    build:
      context: ./user
      <<: *java-build
    environment:
      SERVER_PORT: 8080
      MONGO_URI: mongodb://admin:123456@mongo:27017/studydocs_user_db?authSource=admin
      app.media-service.url: http://media-service:8080
      KEYCLOAK_SERVER_URL: http://keycloak:8080
      KEYCLOAK_CLIENT_SECRET: studydocs-secret
    depends_on:
      <<: [*mongo-dep]
      keycloak:
        condition: service_started

  media-service:
    <<: *java-service
    image: studydocs-media-service:latest
    container_name: studydocs_media_service
    build:
      context: ./media
      <<: *java-build
    env_file:
      - ./media/.env
    depends_on:
      <<: [*postgres-dep]
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  mongo_data:
  redis_data:

secrets:
  GITHUB_TOKEN:
    environment: GITHUB_TOKEN
