server:
  port: 8090
  servlet:
    context-path: /api/v1

spring:
  application:
    name: studydocs-backend
  flyway:
    enabled: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/studydocs?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: studydocs-page-count-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.studydocs.*"
jwt:
  secret: ${JWT_SECRET:studydocsSecretKeySuperLongAndSecureForJwtSigning1234567890}
  expiration-ms: 86400000 # 24 hours
  refresh-expiration-ms: 604800000 # 7 days

file:
  upload-dir: ${UPLOAD_DIR:uploads}

logging:
  level:
    root: INFO
    com.studydocs: DEBUG

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:}
  api-key: ${CLOUDINARY_API_KEY:}
  api-secret: ${CLOUDINARY_API_SECRET:}


