server:
  port: ${SERVER_PORT:8088}
spring:
  application:
    name: education-service

  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]

  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/studydocs_education_db}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
