server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: gateway
  reactor:
    context-propagation: auto
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_SERVER_URL}/.well-known/jwks.json
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: ${USER_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/users/**, /auth/**, /documents/**, /reviews/**, /academics/**, /follows/**
              filters:
                - 'RewritePath=/(?<segment>.*), /api/v1/$\{segment}'
                - name: RequestRateLimiter
                  args:
                    key-resolver: "#{@ipKeyResolver}"
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20

            - id: media-service
              uri: ${MEDIA_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/media/**
              filters:
                - 'RewritePath=/(?<segment>.*), /api/v1/$\{segment}'

          forwarded:
            enabled: true

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}
app:
  security:
    whitelist:
      public-all: ${APP_SECURITY_WHITELIST_PUBLIC_ALL}
      auth-all: ${APP_SECURITY_WHITELIST_AUTH_ALL}
      password-all: ${APP_SECURITY_WHITELIST_PASSWORD_ALL}
      oauth-all: ${APP_SECURITY_WHITELIST_OAUTH_ALL}
      public-get: ${APP_SECURITY_WHITELIST_PUBLIC_GET}
